// ---> Redirect Action <----
export const SAVE_REDIRECT_PATH = "SAVE_REDIRECT_PATH";
export const CLEAR_REDIRECT_PATH = "CLEAR_REDIRECT_PATH";
// ---> Redirect End <---

// ---> Message Action <----
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
export const CLEAR_MESSAGE= "CLEAR_MESSAGE";
// ---> Message End <---

// ---> Search Action <----
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
// ---> Search End <---

// ---> Auth Action <----
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GOOGLE_REQUEST = "GOOGLE_REQUEST";
export const GOOGLE_SUCCESS = "GOOGLE_SUCCESS";
export const GOOGLE_FAILURE = "GOOGLE_FAILURE";

export const SET_USER = "SET_USER ";
export const UPDATE_USER_PROFILE_ITEM = 'UPDATE_USER_PROFILE_ITEM';

export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const SIGNUP_REQUEST = "SIGNIN_REQUEST";
export const SIGNUP_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNUP_FAILURE = "SIGNIN_FAILURE";

export const FORGETPASSWORD_REQUEST = "FORGETPASSWORD_REQUEST";
export const FORGETPASSWORD_SUCCESS = "FORGETPASSWORD_SUCCESS";

export const RESETPASSWORD_REQUEST = "RESETPASSWORD_REQUEST";
export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";
export const RESETPASSWORD_FAILURE = "RESETPASSWORD_FAILURE";

export const CHANGEPASSWORD_REQUEST = "CHANGEPASSWORD_REQUEST";
export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS";
export const CHANGEPASSWORD_FAILURE = "CHANGEPASSWORD_FAILURE";

export const CHANGEUSERPASSWORD_REQUEST = "CHANGEUSERPASSWORD_REQUEST";
export const CHANGEUSERPASSWORD_SUCCESS = "CHANGEUSERPASSWORD_SUCCESS";
export const CHANGEUSERPASSWORD_FAILURE = "CHANGEUSERPASSWORD_FAILURE";

export const CLEAR_AUTHRESPONSE = "CLEAR_AUTHRESPONSE";
// ---> Auth End <---


// --->  DASHBOARD Action <----
export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";

export const CLEAR_DASHBOARDRESPONSE = "CLEAR_DASHBOARDRESPONSE";
// --->  DASHBOARD Action <----

// --->  GROUP Action <----
export const GROUP_REQUEST = "GROUP_REQUEST";
export const GROUP_SUCCESS = "GROUP_SUCCESS";
export const GROUP_FAILURE = "GROUP_FAILURE";
// --->  GROUP Action <----


// ---> Admin Wallet Action <----
export const ADMINWALLET_REQUEST = "ADMINWALLET_REQUEST";
export const ADMINWALLET_SUCCESS = "ADMINWALLET_SUCCESS";
export const ADMINWALLET_FAILURE = "ADMINWALLET_FAILURE";

export const ADMINREVENUE_REQUEST = "ADMINREVENUE_REQUEST";
export const ADMINREVENUE_SUCCESS = "ADMINREVENUE_SUCCESS";
export const ADMINREVENUE_FAILURE = "ADMINREVENUE_FAILURE";

export const ADMINTRANSACTION_REQUEST = "ADMINTRANSACTION_REQUEST";
export const ADMINTRANSACTION_SUCCESS = "ADMINTRANSACTION_SUCCESS";
export const ADMINTRANSACTION_FAILURE = "ADMINTRANSACTION_FAILURE";

export const REVENUEWITHDRAWALPAYMENT_REQUEST = "REVENUEWITHDRAWALPAYMENT_REQUEST";
export const REVENUEWITHDRAWALPAYMENT_SUCCESS = "REVENUEWITHDRAWALPAYMENT_SUCCESS";
export const REVENUEWITHDRAWALPAYMENT_FAILURE = "REVENUEWITHDRAWALPAYMENT_FAILURE";
// ---> Admin Wallet End <---


// ---> Profile Action <----
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";

export const EDITPROFILE_REQUEST = "EDITPROFILE_REQUEST";
export const EDITPROFILE_SUCCESS = "EDITPROFILE_SUCCESS";
export const EDITPROFILE_FAILURE = "EDITPROFILE_FAILURE";
export const CLEAR_UPDATE_RESPONSE = "CLEAR_UPDATE_RESPONSE";

export const DELETEUSER_REQUEST = "DELETEUSER_REQUEST";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const DELETEUSER_FAILURE = "DELETEUSER_FAILURE";

export const SETTING_REQUEST = "SETTING_REQUEST";
export const SETTING_SUCCESS = "SETTING_SUCCESS";
export const SETTING_FAILURE = "SETTING_FAILURE";

export const EDITSETTING_REQUEST = "EDITSETTING_REQUEST";
export const EDITSETTING_SUCCESS = "EDITSETTING_SUCCESS";
export const EDITSETTING_FAILURE = "EDITSETTING_FAILURE";
export const CLEAR_SETTING_RESPONSE = "CLEAR_SETTING_RESPONSE";

// ---> Profile End <---


// ---> ORGANIZATION Action <----
export const ORGANIZATION_REQUEST = "ORGANIZATION_REQUEST";
export const ORGANIZATION_SUCCESS = "ORGANIZATION_SUCCESS";
export const ORGANIZATION_FAILURE = "ORGANIZATION_FAILURE";

export const EDITORGANIZATION_REQUEST = "EDITORGANIZATION_REQUEST";
export const EDITORGANIZATION_SUCCESS = "EDITORGANIZATION_SUCCESS";
export const EDITORGANIZATION_FAILURE = "EDITORGANIZATION_FAILURE";
export const CLEAR_ORGANIZATIONUPDATE_RESPONSE = "CLEAR_ORGANIZATIONUPDATE_RESPONSE";

export const ORGANIZATION_GETWITHDRAWALINFO_REQUEST = "ORGANIZATION_GETWITHDRAWALINFO_REQUEST";
export const ORGANIZATION_GETWITHDRAWALINFO_SUCCESS = "ORGANIZATION_GETWITHDRAWALINFO_SUCCESS";
export const ORGANIZATION_GETWITHDRAWALINFO_FAILURE = "ORGANIZATION_GETWITHDRAWALINFO_FAILURE";

export const ORGANIZATION_EDITWITHDRAWALINFO_REQUEST = "ORGANIZATION_EDITWITHDRAWALINFO_REQUEST";
export const ORGANIZATION_EDITWITHDRAWALINFO_SUCCESS = "ORGANIZATION_EDITWITHDRAWALINFO_SUCCESS";
export const ORGANIZATION_EDITWITHDRAWALINFO_FAILURE = "ORGANIZATION_EDITWITHDRAWALINFO_FAILURE";
// ---> ORGANIZATION End <---


// ---> FOLLOWER Action <----
export const FOLLOWER_REQUEST = "FOLLOWER_REQUEST";
export const FOLLOWER_SUCCESS = "FOLLOWER_SUCCESS";
export const FOLLOWER_FAILURE = "FOLLOWER_FAILURE";

export const EDITFOLLOWER_REQUEST = "EDITFOLLOWER_REQUEST";
export const EDITFOLLOWER_SUCCESS = "EDITFOLLOWER_SUCCESS";
export const EDITFOLLOWER_FAILURE = "EDITFOLLOWER_FAILURE";
export const CLEAREDITFOLLOWER_RESPONSE = "CLEAREDITFOLLOWER_RESPONSE";
// ---> FOLLOWER End <---

// ---> Event Action <----
export const EVENT_REQUEST = "EVENT_REQUEST";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENT_FAILURE = "EVENT_FAILURE";

export const EVENTDETAIL_REQUEST = "EVENTDETAIL_REQUEST";
export const EVENTDETAIL_SUCCESS = "EVENTDETAIL_SUCCESS";
export const EVENTDETAIL_FAILURE = "EVENTDETAIL_FAILURE";

export const CREATEEVENT_REQUEST = "CREATEEVENT_REQUEST";
export const CREATEEVENT_SUCCESS = "CREATEEVENT_SUCCESS";
export const CREATEEVENT_FAILURE = "CREATEEVENT_FAILURE";

export const EDITEVENT_REQUEST = "EDITEVENT_REQUEST";
export const EDITEVENT_SUCCESS = "EDITEVENT_SUCCESS";
export const EDITEVENT_FAILURE = "EDITEVENT_FAILURE";

export const DELETEEVENT_REQUEST = "DELETEEVENT_REQUEST";
export const DELETEEVENT_SUCCESS = "DELETEEVENT_SUCCESS";
export const DELETEEVENT_FAILURE = "DELETEEVENT_FAILURE";

export const CLEAREVENT_RESPONSE = "CLEAREVENT_RESPONSE";

// ---> Event End <---

// ---> Ticket Action <----
export const TICKET_REQUEST = "TICKET_REQUEST";
export const TICKET_SUCCESS = "TICKET_SUCCESS";
export const TICKET_FAILURE = "TICKET_FAILURE";

export const CREATETICKET_REQUEST = "CREATETICKET_REQUEST";
export const CREATETICKET_SUCCESS = "CREATETICKET_SUCCESS";
export const CREATETICKET_FAILURE = "CREATETICKET_FAILURE";
export const CLEARCREATETICKET_RESPONSE = "CLEARCREATETICKET_RESPONSE";

export const DELETETICKET_REQUEST = "DELETETICKET_REQUEST";
export const DELETETICKET_SUCCESS = "DELETETICKET_SUCCESS";
export const DELETETICKET_FAILURE = "DELETETICKET_FAILURE";

// ---> Ticket End SCHEDULE <----

// ---> SCHEDULE Action <----
export const SCHEDULE_REQUEST = "SCHEDULE_REQUEST";
export const SCHEDULE_SUCCESS = "SCHEDULE_SUCCESS";
export const SCHEDULE_FAILURE = "SCHEDULE_FAILURE";

export const CREATESCHEDULE_REQUEST = "CREATESCHEDULE_REQUEST";
export const CREATESCHEDULE_SUCCESS = "CREATESCHEDULE_SUCCESS";
export const CREATESCHEDULE_FAILURE = "CREATESCHEDULE_FAILURE";
export const CLEARCREATESCHEDULE_RESPONSE = "CLEARCREATESCHEDULE_RESPONSE";

export const DELETESCHEDULE_REQUEST = "DELETESCHEDULE_REQUEST";
export const DELETESCHEDULE_SUCCESS = "DELETESCHEDULE_SUCCESS";
export const DELETESCHEDULE_FAILURE = "DELETESCHEDULE_FAILURE";

// ---> SCHEDULE End <---


// ---> SPEAKER Action <----
export const SPEAKER_REQUEST = "SPEAKER_REQUEST";
export const SPEAKER_SUCCESS = "SPEAKER_SUCCESS";
export const SPEAKER_FAILURE = "SPEAKER_FAILURE";
export const CLEARSPEAKER_RESPONSE = "CLEARSPEAKER_RESPONSE";

export const CREATESPEAKER_REQUEST = "CREATESPEAKER_REQUEST";
export const CREATESPEAKER_SUCCESS = "CREATESPEAKER_SUCCESS";
export const CREATESPEAKER_FAILURE = "CREATESPEAKER_FAILURE";
export const CLEARCREATESPEAKER_RESPONSE = "CLEARCREATESPEAKER_RESPONSE";

export const DELETESPEAKER_REQUEST = "DELETESPEAKER_REQUEST";
export const DELETESPEAKER_SUCCESS = "DELETESPEAKER_SUCCESS";
export const DELETESPEAKER_FAILURE = "DELETESPEAKER_FAILURE";

// ---> SPEAKER End <---


// ---> Review Action <----
export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_FAILURE = "REVIEW_FAILURE";
export const CLEARREVIEW_RESPONSE = "CLEARREVIEW_RESPONSE";

export const CREATEREVIEW_REQUEST = "CREATEREVIEW_REQUEST";
export const CREATEREVIEW_SUCCESS = "CREATEREVIEW_SUCCESS";
export const CREATEREVIEW_FAILURE = "CREATEREVIEW_FAILURE";
export const CLEARCREATEREVIEW_RESPONSE = "CLEARCREATEREVIEW_RESPONSE";

// ---> Review End <---

// ---> Transaction Action <----
export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";

export const DELETETRANSACTION_REQUEST = "DELETETRANSACTION_REQUEST";
export const DELETETRANSACTION_SUCCESS = "DELETETRANSACTION_SUCCESS";
export const DELETETRANSACTION_FAILURE = "DELETETRANSACTION_FAILURE";
// ---> Transaction End <---


// ---> Booking Action <----
export const BOOKING_REQUEST = "BOOKING_REQUEST";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAILURE = "BOOKING_FAILURE";

export const CREATEBOOKING_REQUEST = "CREATEBOOKING_REQUEST";
export const CREATEBOOKING_SUCCESS = "CREATEBOOKING_SUCCESS";
export const CREATEBOOKING_FAILURE = "CREATEBOOKING_FAILURE";
export const CLEARCREATEBOOKING_STATE = "CLEARCREATEBOOKING_STATE";

export const DETAILBOOKING_REQUEST = "DETAILBOOKING_REQUEST";
export const DETAILBOOKING_SUCCESS = "DETAILBOOKING_SUCCESS";
export const DETAILBOOKING_FAILURE = "DETAILBOOKING_FAILURE";

export const DELETEBOOKING_REQUEST = "DELETEBOOKING_REQUEST";
export const DELETEBOOKING_SUCCESS = "DELETEBOOKING_SUCCESS";
export const DELETEBOOKING_FAILURE = "DELETEBOOKING_FAILURE";

export const VERIFYBOOKING_REQUEST = "VERIFYBOOKING_REQUEST";
export const VERIFYBOOKING_SUCCESS = "VERIFYBOOKING_SUCCESS";
export const VERIFYBOOKING_FAILURE = "VERIFYBOOKING_FAILURE";

export const REGISTERBOOKING_REQUEST = "REGISTERBOOKING_REQUEST";
export const REGISTERBOOKING_SUCCESS = "REGISTERBOOKING_SUCCESS";
export const REGISTERBOOKING_FAILURE = "REGISTERBOOKING_FAILURE";
// ---> Booking End <---


// ---> Revenue Action <----
export const REVENUE_REQUEST = "REVENUE_REQUEST";
export const REVENUE_SUCCESS = "REVENUE_SUCCESS";
export const REVENUE_FAILURE = "REVENUE_FAILURE";

export const DELETEREVENUE_REQUEST = "DELETEREVENUE_REQUEST";
export const DELETEREVENUE_SUCCESS = "DELETEREVENUE_SUCCESS";
export const DELETEREVENUE_FAILURE = "DELETEREVENUE_FAILURE";
// ---> Revenue End <---


// ---> User Action <----
export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const USERSTATUSUPDATE_REQUEST = "USERSTATUSUPDATE_REQUEST";
export const USERSTATUSUPDATE_SUCCESS = "USERSTATUSUPDATE_SUCCESS";
export const USERSTATUSUPDATE_FAILURE = "USERSTATUSUPDATE_FAILURE";

export const DELETEIDUSER_REQUEST = "DELETEIDUSER_REQUEST";
export const DELETEIDUSER_SUCCESS = "DELETEIDUSER_SUCCESS";
export const DELETEIDUSER_FAILURE = "DELETEIDUSER_FAILURE";
// ---> User End <---


// ---> UserAdminEvent Action <----
export const USERADMINEVENT_REQUEST = "USERADMINEVENT_REQUEST";
export const USERADMINEVENT_SUCCESS = "USERADMINEVENT_SUCCESS";
export const USERADMINEVENT_FAILURE = "USERADMINEVENT_FAILURE";

export const USERADMINAPPROVALUPDATE_REQUEST = "USERADMINAPPROVALUPDATE_REQUEST";
export const USERADMINAPPROVALUPDATE_SUCCESS = "USERADMINPAPPROVALPDATE_SUCCESS";
export const USERADMINAPPROVALUPDATE_FAILURE = "USERADMINPAPPROVALPDATE_FAILURE";

export const EVENTACTIVATION_REQUEST = "EVENTACTIVATION_REQUEST";
export const EVENTACTIVATION_SUCCESS = "EVENTACTIVATION_SUCCESS";
export const EVENTACTIVATION_FAILURE = "EVENTACTIVATION_FAILURE";
// ---> UserAdminEvent End <---


// ---> Category Action <----
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";

export const CREATECATEGORY_REQUEST = "CREATECATEGORY_REQUEST";
export const CREATECATEGORY_SUCCESS = "CREATECATEGORY_SUCCESS";
export const CREATECATEGORY_FAILURE = "CREATECATEGORY_FAILURE";

export const UPDATECATEGORY_REQUEST = "UPDATECATEGORY_REQUEST";
export const UPDATECATEGORY_SUCCESS = "UPDATECATEGORY_SUCCESS";
export const UPDATECATEGORY_FAILURE = "UPDATECATEGORY_FAILURE";

export const DELETECATEGORY_REQUEST = "DELETECATEGORY_REQUEST";
export const DELETECATEGORY_SUCCESS = "DELETECATEGORY_SUCCESS";
export const DELETECATEGORY_FAILURE = "DELETECATEGORY_FAILURE";

// ---> Category End  <----


// ---> Favorite Action <----
export const FAVORITE_REQUEST = "FAVORITE_REQUEST";
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";

export const UPDATEFAVORITE_REQUEST = "UPDATEFAVORITE_REQUEST";
export const UPDATEFAVORITE_SUCCESS = "UPDATEFAVORITE_SUCCESS";
export const UPDATEFAVORITE_FAILURE = "UPDATEFAVORITE_FAILURE";

// --->   Favorite End<----


// ---> Notificationtion Action <----
export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATIONPOP_SUCCESS = "NOTIFICATIONPOP_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";

export const NOTIFICATIONDETAIL_REQUEST = "NOTIFICATIONDETAIL_REQUEST";
export const NOTIFICATIONDETAIL_SUCCESS = "NOTIFICATIONDETAIL_SUCCESS";
export const NOTIFICATIONDETAIL_FAILURE = "NOTIFICATIONDETAIL_FAILURE";

export const CREATENOTIFICATION_REQUEST = "CREATENOTIFICATION_REQUEST";
export const CREATENOTIFICATION_SUCCESS = "CREATENOTIFICATION_SUCCESS";
export const CREATENOTIFICATION_FAILURE = "CREATENOTIFICATION_FAILURE";

export const DELETENOTIFICATION_REQUEST = "DELETENOTIFICATION_REQUEST";
export const DELETENOTIFICATION_SUCCESS = "DELETENOTIFICATION_SUCCESS";
export const DELETENOTIFICATION_FAILURE = "DELETENOTIFICATION_FAILURE";

export const MARKALL_REQUEST = "MARKALL_REQUEST";
export const MARKALL_SUCCESS = "MARKALL_SUCCESS";
export const MARKALL_FAILURE = "MARKALL_FAILURE";
// ---> Notificationtion End  <----


// ---> Side Display Action <----
export const SIDEDISPLAY_REQUEST = "SIDEDISPLAY_REQUEST";
export const SIDEDISPLAY_SUCCESS = "SIDEDISPLAY_SUCCESS";
export const SIDEDISPLAY_FAILURE = "SIDEDISPLAY_FAILURE";

// --->   Side Display End<----


// ---> Payment Action <----
export const INITIALIZATION_REQUEST = "INITIALIZATION_REQUEST";
export const INITIALIZATION_SUCCESS = "INITIALIZATION_SUCCESS";
export const INITIALIZATION_FAILURE = "INITIALIZATION_FAILURE";

export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILURE = "VERIFICATION_FAILURE";

export const CLEARPAYMENT_RESPONSE = "CLEARPAYMENT_RESPONSE";
// --->   Payment End<----